-- Pure-core tests for nice-sidebar.yazi. Loaded by tests/run.lua, which
-- provides the globals t(name, fn), eq(got, want), and core (= M.core).

-- expand -------------------------------------------------------------------
t("expand: bare tilde is home", function()
	eq(core.expand("~", "/Users/u"), "/Users/u")
end)
t("expand: tilde-slash prefixes home", function()
	eq(core.expand("~/Desktop", "/Users/u"), "/Users/u/Desktop")
end)
t("expand: absolute paths pass through", function()
	eq(core.expand("/Volumes/X", "/Users/u"), "/Volumes/X")
end)
t("expand: tilde in the middle is not expanded", function()
	eq(core.expand("/a/~/b", "/Users/u"), "/a/~/b")
end)

-- abbrev -------------------------------------------------------------------
t("abbrev: home becomes tilde", function()
	eq(core.abbrev("/Users/u", "/Users/u"), "~")
end)
t("abbrev: home prefix becomes tilde-slash", function()
	eq(core.abbrev("/Users/u/Projects/x", "/Users/u"), "~/Projects/x")
end)
t("abbrev: sibling of home is untouched", function()
	eq(core.abbrev("/Users/uu/x", "/Users/u"), "/Users/uu/x")
end)
t("abbrev: outside home is untouched", function()
	eq(core.abbrev("/Volumes/X", "/Users/u"), "/Volumes/X")
end)

-- truncate -----------------------------------------------------------------
t("truncate: short strings pass through", function()
	eq(core.truncate("abc", 5), "abc")
end)
t("truncate: exact fit passes through", function()
	eq(core.truncate("abcde", 5), "abcde")
end)
t("truncate: long strings clip with ellipsis", function()
	eq(core.truncate("abcdef", 5), "abcd…")
end)
t("truncate: multibyte characters count as one", function()
	eq(core.truncate("ábçdéf", 5), "ábçd…")
end)
t("truncate: max of one is just the ellipsis", function()
	eq(core.truncate("abc", 1), "…")
end)

-- step ---------------------------------------------------------------------
t("step: empty list yields nil", function()
	eq(core.step(nil, 1, 0), nil)
end)
t("step: no selection targets the first item, either direction", function()
	eq(core.step(nil, 1, 5), 1)
	eq(core.step(nil, -1, 5), 1)
end)
t("step: moves by delta", function()
	eq(core.step(2, 1, 5), 3)
	eq(core.step(2, -1, 5), 1)
end)
t("step: clamps at both ends", function()
	eq(core.step(1, -1, 5), 1)
	eq(core.step(5, 1, 5), 5)
end)

-- inside -------------------------------------------------------------------
t("inside: equal paths match", function()
	eq(core.inside("/a/b", "/a/b"), true)
end)
t("inside: descendants match", function()
	eq(core.inside("/a/b", "/a/b/c/d"), true)
end)
t("inside: component boundaries are respected", function()
	eq(core.inside("/a/b", "/a/bc"), false)
end)
t("inside: parents do not match", function()
	eq(core.inside("/a/b", "/a"), false)
end)
t("inside: root umbrella holds everything", function()
	eq(core.inside("/", "/anything/at/all"), true)
end)

-- track --------------------------------------------------------------------
local items = {
	{ label = "Home", path = "/Users/u", icon = "h" },
	{ label = "Desktop", path = "/Users/u/Desktop", icon = "d" },
	{ label = "Disk", path = "/Volumes/X", icon = "x" },
}
t("track: exact match wins over an umbrella hold", function()
	eq(core.track(items, 1, "/Users/u/Desktop"), 2)
end)
t("track: exact match adopts even with no selection", function()
	eq(core.track(items, nil, "/Volumes/X"), 3)
end)
t("track: duplicate paths resolve to the first in list order", function()
	local dup = { { path = "/p" }, { path = "/p" } }
	eq(core.track(dup, 2, "/p"), 1)
end)
t("track: umbrella keeps the selection", function()
	eq(core.track(items, 2, "/Users/u/Desktop/stuff"), 2)
end)
t("track: leaving the umbrella clears", function()
	eq(core.track(items, 3, "/private/tmp"), nil)
end)
t("track: no selection and no exact match stays clear", function()
	eq(core.track(items, nil, "/Users/u/Desktop/stuff"), nil)
end)

-- window -------------------------------------------------------------------
t("window: everything fits", function()
	local first, last = core.window(5, 10, 3)
	eq({ first, last }, { 1, 5 })
end)
t("window: centers on the anchor", function()
	local first, last = core.window(20, 5, 10)
	eq({ first, last }, { 8, 12 })
end)
t("window: clamps at the top", function()
	local first, last = core.window(20, 5, 1)
	eq({ first, last }, { 1, 5 })
end)
t("window: clamps at the tail", function()
	local first, last = core.window(20, 5, 20)
	eq({ first, last }, { 16, 20 })
end)
t("window: nil anchor pins to the top", function()
	local first, last = core.window(20, 5, nil)
	eq({ first, last }, { 1, 5 })
end)

-- build --------------------------------------------------------------------
local dirs = { { label = "Home", path = "/u", icon = "h" }, { label = "Desk", path = "/u/d", icon = "d" } }
t("build: dirs only — title block, no sections", function()
	local rows, its = core.build({ dirs = dirs, pins = {}, disks = {} })
	eq(#its, 2)
	eq(rows[1], { type = "title" })
	eq(rows[2], { type = "rule" })
	eq(rows[3], { type = "blank" })
	eq(rows[4], { type = "item", index = 1 })
	eq(rows[5], { type = "item", index = 2 })
	eq(#rows, 5)
end)
t("build: empty pins hide the whole Pinned section", function()
	local rows = core.build({ dirs = dirs, pins = {}, disks = { { label = "X", path = "/Volumes/X", icon = "x" } } })
	for _, row in ipairs(rows) do
		if row.type == "header" then
			eq(row.text, "Disks")
		end
	end
end)
t("build: sections carry header, inset rule, and items in order", function()
	local rows, its = core.build({
		dirs = dirs,
		pins = { { label = "~/p", path = "/u/p", icon = "p" } },
		disks = { { label = "X", path = "/Volumes/X", icon = "x" } },
	})
	eq(#its, 4)
	eq(rows[6], { type = "blank" })
	eq(rows[7], { type = "header", text = "Pinned", icon = "󰐃" })
	eq(rows[8], { type = "rule", inset = true })
	eq(rows[9], { type = "item", index = 3 })
	eq(rows[10], { type = "blank" })
	eq(rows[11], { type = "header", text = "Disks", icon = "󰋊" })
	eq(rows[12], { type = "rule", inset = true })
	eq(rows[13], { type = "item", index = 4 })
	eq(its[3].path, "/u/p")
	eq(its[4].path, "/Volumes/X")
end)

-- toggle -------------------------------------------------------------------
t("toggle: adds a missing path", function()
	eq(core.toggle({ "/a" }, "/b"), { "/a", "/b" })
end)
t("toggle: removes a present path", function()
	eq(core.toggle({ "/a", "/b" }, "/a"), { "/b" })
end)
t("toggle: drops duplicates and relative junk on rewrite", function()
	eq(core.toggle({ "/a", "/a", "junk", "" }, "/b"), { "/a", "/b" })
end)
t("toggle: refuses to add a non-absolute path", function()
	eq(core.toggle({ "/a" }, "junk"), { "/a" })
end)

-- disk_kind ----------------------------------------------------------------
t("disk_kind: disk images by protocol", function()
	eq(core.disk_kind("   Protocol:                  Disk Image\n   Internal:                  No"), "image")
end)
t("disk_kind: internal fixed disks", function()
	eq(core.disk_kind("   Protocol:                  Apple Fabric\n   Internal:                  Yes"), "internal")
end)
t("disk_kind: everything else is external", function()
	eq(core.disk_kind("   Protocol:                  USB\n   Internal:                  No"), "external")
end)
t("disk_kind: unparseable output falls back to external", function()
	eq(core.disk_kind(""), "external")
end)
